# Generated by Django 5.2.8 on 2025-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igaccesstoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='igbusinessaccount',
            name='business_id',
        ),
        migrations.AddField(
            model_name='igbusinessaccount',
            name='business_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igbusinessaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igbusinessaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AlterField(
            model_name='igaccesstoken',
            name='access_token',
            field=models.TextField(unique=True),
        ),
    ]
