# Generated by Django 5.2.8 on 2025-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_igaccesstoken_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igbusinessaccount',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='l_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
