# Generated by Django 5.2.8 on 2026-03-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_igbusinessaccount_auto_reply_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igbusinessaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
